# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIcQPYhGoukROGgxPImzZdL698TZLv6g

# **Task 1: Perform Basic Mathematical Operations**
Problem Statement: Write a Python program that does the following:
1.  Takes two numbers as input from the user.
2.  Performs the basic mathematical operations on these two numbers:
o	Addition
o	Subtraction
o	Multiplication
o	Division
3.  Displays the results of each operation on the screen.
"""

N1=int(input("Please enter the first number: "))
N2=int(input("Please enter the second number: "))
sum=print("Addition:",N1+N2)
Subtrcation=print("Subtraction:",N1-N2)
Multiplication=print("Multiplication:",N1*N2)
Division= print("Division:",N1/N2)

"""# **Task 2: Create a Personalized Greeting**
Problem Statement: Write a Python program that:
1.  Takes a user's first name and last name as input.
2.  Concatenates the first name and last name into a full name.
3.  Prints a personalized greeting message using the full name.

"""



F1=str(input("Enter your first name: "))
L1=str(input("Enter your last name: "))
Full_name= F1+' '+L1
print('Hello '+Full_name+ "! Welcome to the python Program.")

